# -*- mode: ruby -*-
# vi: set ft=ruby :

#ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
CPUS="1"
MEMORY="1024"

Vagrant.configure("2") do |config|

  config.vm.define "ubuntu_lab" do |config|
  config.vm.hostname = "ubuntu-lab"
  config.vm.box = "peru/ubuntu-20.04-server-amd64"
  config.vm.box_version = "20200424.01"
  
  config.vm.provider :libvirt do |v|

    v.driver = "kvm"
    v.memory = MEMORY
    v.cpus = CPUS
  end
end
end
